services:
  discord-always-on:
    image: discord-always-on
    build:
      context: DiscordAlwaysOn
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json
#    environment:
#      - "AlwaysOn:TOKEN="
#      - "AlwaysOn:Activities=[]"
#      - "AlwaysOn:Status=idle"
#      - "AlwaysOn:Afk=true"
